---
  extends: airbnb-base
  env:
    browser: true
    mocha: true
    es6: true
  rules:
    indent: [2,4]
    func-names: 0
    vars-on-top: 0
    one-var: 0
    radix: 'off'
    no_underscore_dangle: 0
    class-methods-use-this: 0
    quote-props: 0
    no-trailing-spaces: 0
